repos:
-   repo: local
    hooks:
    -   id: check-secrets
        name: check secrets in files
        language: script
        entry: .check-secrets.sh
        always_run: true
        verbose: true
        stages: ["push"]

